name: Code Linter

on:
  pull_request:
    branches: [ main ]

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pylint
        run: pip install pylint

      - name: Run Pylint everywhere
        if: github.actor != 'maxred01'
        run: |
          find . -name "*.py" | xargs pylint --exit-zero

      - name: Bypass for teacher
        if: github.actor == 'maxred01'
        run: echo "Проверка пропущена (преподаватель)" && exit 0
