name: Pylint Check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pylint
        run: |
          pip install --upgrade pylint

      - name: Check teacher access
        id: check_teacher
        env:
          TEACHERS: ${{ secrets.TEACHERS }}
        run: |
          if [[ "$TEACHERS" == *"${{ github.actor }}"* ]]; then
            echo "teacher_override=true" >> $GITHUB_OUTPUT
          else
            echo "teacher_override=false" >> $GITHUB_OUTPUT
          fi

      - name: Run pylint
        if: steps.check_teacher.outputs.teacher_override != 'true'
        run: |
          pylint $(git ls-files '*.py') || exit 1  # Строгий режим: ошибка при любом warning
